In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\omkar\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\omkar\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\omkar\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\omkar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\omkar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\omkar\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
#pandas

In [4]:
#install pandas

In [5]:
import pandas as pd

In [6]:
s =pd.Series([10,20,30])

In [8]:
s

0    10
1    20
2    30
dtype: int64

In [9]:
type(s)

pandas.core.series.Series

In [10]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [11]:
s

a    10
b    20
c    30
dtype: int64

In [12]:
dic={
    "name":"sayali",
    "age":"17",
    "marks":71.77
}

In [13]:
print(dic)

{'name': 'sayali', 'age': '17', 'marks': 71.77}

In [15]:
s=pd.Series(dic)

In [16]:
s

name     sayali
age          17
marks     71.77
dtype: object

In [19]:
pd.Series(5,index=['0','1','2','3','4'])

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [32]:
s1=pd.Series([10,20,30],index=['a','b','c'])

In [25]:
s1

a    10
b    20
c    30
dtype: int64

In [26]:
s1.values

array([10, 20, 30])

In [27]:
s1.index

Index(['a', 'b', 'c'], dtype='object')

In [28]:
s1.dtype

dtype('int64')

In [29]:
s1.shape

(3,)

In [30]:
s1*2

a    20
b    40
c    60
dtype: int64

In [35]:
s1=pd.Series([10,None,30])

In [36]:
s1

0    10.0
1     NaN
2    30.0
dtype: float64

In [38]:
s1.isnull()

0    False
1     True
2    False
dtype: bool

In [39]:
s1.dropna()

0    10.0
2    30.0
dtype: float64

In [40]:
s1.fillna(5)

0    10.0
1     5.0
2    30.0
dtype: float64

In [44]:
s=pd.Series([1,2,2,3,3,3])

In [45]:
s

0    1
1    2
2    2
3    3
4    3
5    3
dtype: int64

In [47]:
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [48]:
s=pd.Series([10,20,30,40],index=['a','b','c','d'])

In [49]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [50]:
s['a']

np.int64(10)

In [51]:
s['b']

np.int64(20)

In [54]:
#dataframe create

In [58]:
Data ={
    "Roll_N0":[100,200,300,400],
    "name":["Sayali","Tanishka","pallavi","Bhaguu"],
    "marks":[99,101,100,98]
}

In [59]:
Data

{'Roll_N0': [100, 200, 300, 400],
 'name': ['Sayali', 'Tanishka', 'pallavi', 'Bhaguu'],
 'marks': [99, 101, 100, 98]}

In [60]:
df=pd.DataFrame(Data)

In [61]:
df

   Roll_N0      name  marks
0      100    Sayali     99
1      200  Tanishka    101
2      300   pallavi    100
3      400    Bhaguu     98

In [2]:
Data ={
    "Subject":["java","python","OOP"],
    "Marks":[99,98,97,95],
    "Grade":['A','B','C']
}

In [3]:
Data

{'Subject': ['java', 'python', 'OOP'],
 'Marks': [99, 98, 97, 95],
 'Grade': ['A', 'B', 'C']}

In [68]:
df.to_csv('marks_data.csv',index=False)

In [69]:
df = pd.read_csv("marks_data.csv")

In [70]:
df

   Roll_N0      name  marks
0      100    Sayali     99
1      200  Tanishka    101
2      300   pallavi    100
3      400    Bhaguu     98

In [72]:
df.head()

   Roll_N0      name  marks
0      100    Sayali     99
1      200  Tanishka    101
2      300   pallavi    100
3      400    Bhaguu     98

In [76]:
df.tail()

   Roll_N0      name  marks
0      100    Sayali     99
1      200  Tanishka    101
2      300   pallavi    100
3      400    Bhaguu     98

In [77]:
df.shape

(4, 3)

In [84]:
df.columns

Index(['Roll_N0', 'name', 'marks'], dtype='object')

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll_N0  4 non-null      int64
 1   name     4 non-null      object
 2   marks    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [87]:
df.describe()

          Roll_N0       marks
count    4.000000    4.000000
mean   250.000000   99.500000
std    129.099445    1.290994
min    100.000000   98.000000
25%    175.000000   98.750000
50%    250.000000   99.500000
75%    325.000000  100.250000
max    400.000000  101.000000

In [90]:
df.isnull().sum

<bound method DataFrame.sum of    Roll_N0   name  marks
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False>

In [91]:
df = df.drop_duplicates()

In [92]:
df

   Roll_N0      name  marks
0      100    Sayali     99
1      200  Tanishka    101
2      300   pallavi    100
3      400    Bhaguu     98

In [95]:
df['marks']=df['marks'].astype(float)

In [96]:
df

   Roll_N0      name  marks
0      100    Sayali   99.0
1      200  Tanishka  101.0
2      300   pallavi  100.0
3      400    Bhaguu   98.0

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll_N0  4 non-null      int64
 1   name     4 non-null      object
 2   marks    4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes

In [102]:
df["marks"]

0     99.0
1    101.0
2    100.0
3     98.0
Name: marks, dtype: float64

In [103]:
df["name"]

0      Sayali
1    Tanishka
2     pallavi
3      Bhaguu
Name: name, dtype: object

In [106]:
df[["name","marks"]]

       name  marks
0    Sayali   99.0
1  Tanishka  101.0
2   pallavi  100.0
3    Bhaguu   98.0

In [107]:
df=df.sort_values(by="marks",ascending=False)

In [108]:
df

   Roll_N0      name  marks
1      200  Tanishka  101.0
2      300   pallavi  100.0
0      100    Sayali   99.0
3      400    Bhaguu   98.0